security:

    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        users:
            entity:
                class: 'App\Entity\User'
                property: 'username'

    firewalls:
        main:
            anonymous: lazy
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }